import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import Flickity from 'react-flickity-component'
import 'flickity/dist/flickity.min.css';

const inter = Inter({ subsets: ['latin'] })
type slide = {
  image: string;
  alt: string;
  title: string;
};

export default function Home() {
  const [slides, setSlides] = useState<null | slide[]>();

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async() => {
    fetch('slides/buffalo-slider.json')
      .then(res => {
        res.json().then(data => {
          setSlides(data);
        })
      })
  }

  return (
    <>
      <Head>
        <title>Robot Kitten - Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            an escape from<br/>
            a dystopian world
          </p>
        </div>

        <Flickity
          className={styles.carousel}
          elementType={'div'}
          options={{
            pageDots: false,
            wrapAround: true,
            draggable: true,
            prevNextButtons: true,
            imagesLoaded: true,
            bgLazyLoad: true,
            setGallerySize: true,
            initialIndex: 1,
          }}
          disableImagesLoaded={false}
          reloadOnUpdate
          static
        >
          {slides?.map((slide, idx) => (
              <div
                key={idx}
                className={styles.cell + " carousel-cell"}
              >
                <img
                  className={styles.logo}
                  src={`/slides/${slide.image}`}
                  alt={slide.title}
                />
                <span className={styles.counter}>{`${idx + 1}/${slides.length}`}</span>
              </div>
            ))
          }
        </Flickity>

        <div className={styles.grid}>
          <div>
            <div className={styles.more}>
              More about
            </div>
            <div className={styles.link}>
              <span>www.shop.gruppemagazine.com</span>
              <img src="external.svg" alt="link" />
            </div>
            <div className={styles.socials}>
              <img
                style={{ objectFit: 'contain'}}
                src="/logos/instagram.png"
                alt="instagram"
              />
              <img
                style={{ objectFit: 'contain'}}
                src="/logos/facebook.png"
                alt="facebook"
              />
              <img
                style={{ objectFit: 'contain'}}
                src="/logos/youtube.png"
                alt="youtube"
              />
              <img
                style={{ objectFit: 'contain'}}
                src="/logos/linkedin.png"
                alt="linkedin"
              />
              <img
                style={{ objectFit: 'contain'}}
                src="/logos/tiktok.png"
                alt="tiktok"
              />
            </div>
          </div>
          <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque facilisis vehicula sapien et iaculis. Donec eu erat ipsum. Nulla lorem velit, fermentum vitae dui in, fermentum congue dolor. Vestibulum rutrum condimentum est, sed tincidunt orci egestas id.
          </div>
        </div>
      </main>
    </>
  )
}
